[derive] IntoBytes padding error says number of bytes (#2699)
While we're here, always say "padding" instead of "inter-field padding",
as all kinds (structs, enums, and unions) can have trailing padding too.

As an example, the diff for
`zerocopy-derive/tests/ui-stable/enum.stderr` contains:

-error[E0277]: `IntoBytes3` has inter-field padding
+error[E0277]: `IntoBytes3` has 2 total byte(s) of padding

Closes #1717